services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: curupira_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/curupira_dev
      MIX_ENV: dev
      RELEASE_NODE: curupira
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - mix_deps:/app/deps
      - static_files:/static_html
    working_dir: /app

  static:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - static_files:/usr/share/nginx/html:ro
    depends_on:
      - web

volumes:
  postgres_data:
  mix_deps:
  static_files:
